name: Wails build

on:
  push:
    tags:
    # Match any new tag
      - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: wailsTest, platform: windows/amd64, os: windows-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          node-version: 22.13.0
          package: true
          build-tags: with_gvisor