name: Wails build

on:
  push:
    tags:
    # Match any new tag
      - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: platform-vpn-linux, platform: linux/amd64, os: ubuntu-latest},
          {name: platform-vpn-windows, platform: windows/amd64, os: windows-latest},
          {name: platform-vpn-darwin.app, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Linux Wails deps
        if: matrix.build.os == 'ubuntu-latest'
        run: sudo apt-get update -y && sudo apt-get install -y libwebkit2gtk-4.1-dev
      
      - name: Build wails
        uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          node-version: 22.13.0
          package: true
          build-tags: with_gvisor,webkit2_41

      
      - name: Build wails
        uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          node-version: 22.13.0
          package: true
          build-tags: with_gvisor